/**
 * ACTION CONSTANTS
 */
export default {
  UPDATE_LIVE_CONFIG: 'UPDATE_LIVE_CONFIG', // 更新直播配置
  UPDATE_PUSHER_CONFIG: 'UPDATE_PUSHER_CONFIG', // 更新推流配置
  UPDATE_LIVING_INFO: 'UPDATE_LIVING_INFO', // 正在直播的直播间信息(观看、推流)
  UPDATE_LIVING_STATUS: 'UPDATE_LIVING_STATUS', // 正在观看的直播状态
  UPDATE_ANCHOR_LIVING_STATUS: 'UPDATE_ANCHOR_LIVING_STATUS', // 推流端状态
}