/**
 * 主播店铺数据
 */

 export default {
  UPDATE_RETURN_ADDRESS: 'UPDATE_RETURN_ADDRESS', // 更新寄回地址
  UPDATE_SHOP_GOODS: 'UPDATE_SHOP_GOODS', // 更新店铺商品
  UPDATE_SHOWCASE_GOODS: 'UPDATE_SHOWCASE_GOODS', // 主播橱窗商品
  UPDATE_WAREHOUSE_GOODS: 'UPDATE_WAREHOUSE_GOODS', // 主播预组货商品
  UPDATE_PERSONAL_GOODS: 'UPDATE_PERSONAL_GOODS', // 个人店铺商品
  UPDATE_PLATFORM_BRNDS: 'UPDATE_PLATFORM_BRNDS', // 平台品牌
  UPDATE_PLATFORM_GOODS: 'UPDATE_PLATFORM_GOODS', // 品牌商品
 }
